### PR TITLE
[FLINK-1731] [ml] Implementation of Feature K-Means and Test Suite

### PR DESCRIPTION
**Pull request by peterschrott**
Merging this fork into @sachingoel0101 fork for convenience of code review by committers. 

See: https://github.com/apache/flink/pull/700

### CODE REVIEW

**Comment by sachingoel0101** [comment]
Merging. @peedeeX21

**Comment by peterschrott** [comment]
@sachingoel0101 nice. thanks.
is there something wrong with your repo, as i could not choose it?

**Comment by sachingoel0101** [comment]
No. I faced this same issue yesterday. Apparently, I was unable to see your fork as base fork too. I don't know how but manipulating the URL directly seemed to work.

**Comment by peterschrott** [comment]
oke. that's strange. I guess we are not supposed to work together. :(  It works perfectly with my colleagues. Anyway, good luck ...

**Pull request merged**
